{atualizaPermissoes(input:"{\"groupName\":\"orggroup-d8183c60-c279-45f3-be6e-5ccafd82d5d2\",\"modelsGroups\":[{\"ModelName\":\"Api\",\"Permissao\":\"RW\"},{\"ModelName\":\"EntradaApi\",\"Permissao\":\"RW\"},{\"ModelName\":\"Aplicacao\",\"Permissao\":\"RW\"},{\"ModelName\":\"Symphonia\",\"Permissao\":\"RW\"},{\"ModelName\":\"Score\",\"Permissao\":\"RW\"},{\"ModelName\":\"Org\",\"Permissao\":\"RW\"},{\"ModelName\":\"Model\",\"Permissao\":\"RW\"},{\"ModelName\":\"Campo\",\"Permissao\":\"RW\"},{\"ModelName\":\"Enum\",\"Permissao\":\"RW\"},{\"ModelName\":\"Modulo\",\"Permissao\":\"RW\"},{\"ModelName\":\"Tela\",\"Permissao\":\"RW\"},{\"ModelName\":\"Card\",\"Permissao\":\"RW\"},{\"ModelName\":\"AmplifyFormVue\",\"Permissao\":\"RW\"},{\"ModelName\":\"CampoFormEstilo\",\"Permissao\":\"RW\"},{\"ModelName\":\"TabelaSyncFusion\",\"Permissao\":\"RW\"}]}")}
{atualizaPermissoes(input:"{\"groupName\":\"98213e8b-admin\",\"modelsGroups\":[{\"ModelName\":\"Api\",\"Permissao\":\"RW\"},{\"ModelName\":\"EntradaApi\",\"Permissao\":\"RW\"},{\"ModelName\":\"Aplicacao\",\"Permissao\":\"RW\"},{\"ModelName\":\"Symphonia\",\"Permissao\":\"RW\"},{\"ModelName\":\"Score\",\"Permissao\":\"RW\"},{\"ModelName\":\"Org\",\"Permissao\":\"RW\"},{\"ModelName\":\"Model\",\"Permissao\":\"RW\"},{\"ModelName\":\"Campo\",\"Permissao\":\"RW\"},{\"ModelName\":\"Enum\",\"Permissao\":\"RW\"},{\"ModelName\":\"Modulo\",\"Permissao\":\"RW\"},{\"ModelName\":\"Tela\",\"Permissao\":\"RW\"},{\"ModelName\":\"Card\",\"Permissao\":\"RW\"},{\"ModelName\":\"AmplifyFormVue\",\"Permissao\":\"RW\"},{\"ModelName\":\"CampoFormEstilo\",\"Permissao\":\"RW\"},{\"ModelName\":\"TabelaSyncFusion\",\"Permissao\":\"RW\"}]}")}